export default class Client {
    constructor(
      public email: string,
      public clientName: string,
      public attendedDate: Date,
      public contactNumber: string,
      public address: string,
      public productName: string,
      public quantity: string,
      public version: string,
      public brand: string,
      public model: string,
      public warrantyDate: Date,
      public guaranteeDate: Date,
      public _id?: string, // Optional field for the ID, assuming it's generated by the database
    ) {}
  }
  
